import type { CSSProperties } from "react";

export const uiStyles: { [key: string]: CSSProperties } = {
  wrapper: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "#121212",
    padding: "10px",
    boxSizing: "border-box",
    fontFamily: "monospace",
  },
  gameContainer: {
    width: "100%",
    maxWidth: "800px",
    aspectRatio: "16/9",
    display: "flex",
    flexDirection: "column",
    border: "4px solid #000",
    background: "#B3F1FF",
    position: "relative",
    overflow: "hidden",
    borderRadius: "12px",
  },
  world: {
    flex: 1,
    position: "relative",
    overflow: "hidden",
    borderBottom: "4px solid #000",
  },
  background: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: "40px",
    backgroundRepeat: "repeat-x",
    backgroundSize: "40px 40px",
    zIndex: 5,
  },
  entity: {
    position: "absolute",
    width: "56px",
    height: "56px",
    transform: "translateY(-100%)",
  },
  spriteLayer: {
    backgroundPosition: "bottom center",
    backgroundRepeat: "no-repeat",
    imageRendering: "pixelated",
  },
  fireball: {
    position: "absolute",
    background: "#ff4500",
    borderRadius: "50%",
    zIndex: 15,
    border: "2px solid #fff",
    boxShadow: "0 0 10px #ff4500",
  },
  hpBarBg: {
    position: "absolute",
    top: -12,
    width: "56px",
    height: "6px",
    background: "#333",
    border: "1.5px solid #000",
  },
  hpBarFill: {
    height: "100%",
    background: "#ff4d4d",
    transition: "width 0.3s ease",
  },
  targetArrow: {
    position: "absolute",
    top: -45,
    left: "28px",
    transform: "translateX(-50%)",
    color: "yellow",
    fontSize: "16px",
    textShadow: "2px 2px #000",
  },
  damageText: {
    position: "absolute",
    fontWeight: "900",
    fontSize: "26px",
    textShadow: "2px 2px 0px #000",
    pointerEvents: "none",
    zIndex: 999,
    width: "80px",
    textAlign: "center",
  },
  overlay: {
    position: "absolute",
    inset: 0,
    background: "rgba(0,0,0,0.85)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  },
  restartBtn: {
    padding: "12px 24px",
    background: "#ffeb3b",
    border: "4px solid #000",
    fontWeight: "bold",
    cursor: "pointer",
    marginTop: "20px",
  },
  panel: {
    background: "#2c2c2c",
    display: "flex",
    padding: "12px",
    gap: "12px",
    borderTop: "4px solid #000",
  },
  wordSection: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  actionRow: {
    display: "flex",
    gap: "10px",
    justifyContent: "space-between",
    alignItems: "center",
  },
  slotContainer: { display: "flex", gap: "6px" },
  slot: {
    width: "45px",
    height: "45px",
    background: "#444",
    border: "2px solid #000",
    borderRadius: "8px",
  },
  letterCard: {
    width: "42px",
    height: "42px",
    background: "#f2a654",
    border: "2px solid #000",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontWeight: "bold",
    cursor: "pointer",
    position: "relative",
    borderRadius: "4px",
    color: "#000",
  },
  scoreTag: { position: "absolute", bottom: 1, right: 2, fontSize: "8px" },
  inventory: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    background: "#111",
    padding: "10px",
    borderRadius: "8px",
    minHeight: "100px",
    border: "2px solid #444",
  },
  actionBtn: {
    padding: "8px 12px",
    border: "3px solid #000",
    fontWeight: "bold",
    borderRadius: "6px",
    fontSize: "12px",
    cursor: "pointer",
    minWidth: "70px",
  },
  meaningTag: {
    position: "absolute",
    bottom: "50%",
    left: "50%",
    transform: "translateX(-50%)",
    background: "rgba(0,0,0,0.85)",
    color: "#00ffcc",
    padding: "6px 16px",
    borderRadius: "20px",
    border: "2px solid #00ffcc",
    fontSize: "14px",
    fontWeight: "bold",
    zIndex: 50,
  },
};